"use strict";var l=Object.defineProperty;var h=Object.getOwnPropertyDescriptor;var R=Object.getOwnPropertyNames;var v=Object.prototype.hasOwnProperty;var i=(r,e)=>l(r,"name",{value:e,configurable:!0});var f=(r,e)=>{for(var o in e)l(r,o,{get:e[o],enumerable:!0})},E=(r,e,o,a)=>{if(e&&typeof e=="object"||typeof e=="function")for(let t of R(e))!v.call(r,t)&&t!==o&&l(r,t,{get:()=>e[t],enumerable:!(a=h(e,t))||a.enumerable});return r};var p=r=>E(l({},"__esModule",{value:!0}),r);var m={};f(m,{AwsContextResolver:()=>c});module.exports=p(m);var c=class{static{i(this,"AwsContextResolver")}createResolver({context:e,event:o,log:a,respondWithErrors:t,adapter:d}){if(!e)throw new Error('Could not figure out how to create the resolver because the "context" argument was not sent.');if(!e.succeed)throw new Error(`Could not figure out how to create the resolver because the "context" argument didn't have the "succeed" function.`);if(!e.fail)throw new Error(`Could not figure out how to create the resolver because the "context" argument didn't have the "fail" function.`);let u={succeed:n=>e.succeed(n),fail:n=>e.fail(n)};return{run:n=>{n().then(s=>u.succeed(s)).catch(s=>{a.error("SERVERLESS_ADAPTER:RESPOND_TO_EVENT_SOURCE_WITH_ERROR",s),d.onErrorWhileForwarding({delegatedResolver:u,error:s,log:a,event:o,respondWithErrors:t})})}}}};0&&(module.exports={AwsContextResolver});
//# sourceMappingURL=index.cjs.map